name: app_ban_tranh_admin
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  image_picker: ^1.1.2 
  file_picker: ^8.1.4  
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  intl: ^0.20.2        
  flutter_lints: ^6.0.0 

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/